CUDA_VISIBLE_DEVICES=0 python3 main.py \
    --pretrain moco \
    --model resnet18 \
    --dataset cifar10 \
    --optimizer adamw \
    --lr 0.0003 \
    --weight_decay 0.0001 \
    --scheduler cos_annealing \
    --T_max 300 \
    --batch_size 256 \
    --logging_step 1 \
    --epoch 100 \
    --logdir ./log_moco_resnet18_0.01/ \
